# Generated by Django 4.0.4 on 2022-05-23 21:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nicknames',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nickname(s)'),
        ),
    ]
