# Generated by Django 4.0.4 on 2022-05-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_birthdate_person_nationality_person_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='person',
            name='strava',
            field=models.CharField(blank=True, max_length=100, verbose_name='Strava'),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter'),
        ),
    ]
