# Generated by Django 4.0.4 on 2022-05-24 03:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_race_start_year_alter_team_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='race',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='race',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='nicknames',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nickname(s)'),
        ),
    ]
