# Generated by Django 4.0.4 on 2022-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person_pronunciation_race_country_race_pronunciation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='teamname',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamname',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
