# Generated by Django 4.0.4 on 2022-05-23 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('preferred_name', models.CharField(max_length=100, verbose_name='Preferred Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
